2019-09-28 13:20:39,342 - interactiontest - DEBUG - EntityDb(call_john): add_entity(sort=u'number_type', grammar_entry='mobile', name=u'mobile')
2019-09-28 13:20:39,342 - interactiontest - DEBUG - EntityDb(call_john): add_entity returns u'mobile'
2019-09-28 13:20:39,342 - interactiontest - DEBUG - EntityDb(call_john): add_entity(sort=u'number_type', grammar_entry='home', name=u'home')
2019-09-28 13:20:39,342 - interactiontest - DEBUG - EntityDb(call_john): add_entity returns u'home'
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity(sort=u'contact_name', grammar_entry='Mary', name=u'contact_mary')
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity returns u'contact_mary'
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity(sort=u'contact_name', grammar_entry="Mary's", name=u'contact_mary')
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity returns u'contact_mary'
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity(sort=u'number_type', grammar_entry='work', name=u'work')
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity returns u'work'
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity(sort=u'contact_name', grammar_entry='John', name=u'contact_john')
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity returns u'contact_john'
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity(sort=u'contact_name', grammar_entry="John's", name=u'contact_john')
2019-09-28 13:20:39,343 - interactiontest - DEBUG - EntityDb(call_john): add_entity returns u'contact_john'
2019-09-28 13:20:39,343 - interactiontest - DEBUG - Backend()
2019-09-28 13:20:39,444 - interactiontest - ERROR - Encountered an error, sending event 'BACKEND_ERROR'
Traceback (most recent call last):
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/backend.py", line 100, in handle_event_from_external_queue
    self._handle_external_event(event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/backend.py", line 113, in _handle_external_event
    resulting_events = self._send_event_through_components(event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/backend.py", line 124, in _send_event_through_components
    moves = self._dm.act(events)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/component.py", line 47, in act
    self._act_on_queued_events()
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/component.py", line 86, in _act_on_queued_events
    self._handle_event(event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/component.py", line 101, in _handle_event
    self.forward_event_internally_and_externally(event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/component.py", line 104, in forward_event_internally_and_externally
    self._event_dispatcher.dispatch(event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/event_dispatcher.py", line 27, in dispatch
    self._send_event_to_subscribing_modules(event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/event_dispatcher.py", line 49, in _send_event_to_subscribing_modules
    handler, event.get_type(), event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/event_dispatcher.py", line 55, in _send_to_subscribing_module
    module.process_event(protected_event)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/lib/module.py", line 50, in process_event
    handler()
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/dme_module.py", line 56, in _handle_interpretation
    self._set_input_event_and_run_update_and_select()
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/dme_module.py", line 61, in _set_input_event_and_run_update_and_select
    self.run_update_and_set_ddd_when_needed()
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/dme_module.py", line 66, in run_update_and_set_ddd_when_needed
    self.run_update()
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/dme_module.py", line 131, in run_update
    self.update_module.run(self._tis)
  File "tdm/dm/update.py", line 166, in tdm.dm.update.UpdateModule.run
  File "tdm/dm/update.py", line 245, in tdm.dm.update.UpdateModule.integrate_moves
  File "tdm/dm/update.py", line 265, in tdm.dm.update.UpdateModule.try_move_integratation_without_accommodation
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/isu_module.py", line 115, in tryGroup
    return self._apply(ruleGroup, identifier, tis)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/isu_module.py", line 139, in _apply
    if self.applyRule(rule, tis):
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/isu_module.py", line 100, in applyRule
    if rule.testPreconditions(self._ddd_manager, tis):
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/isu_rule.py", line 18, in testPreconditions
    return self.preconditions(ddd_manager, self.tis)
  File "tdm/dm/update.py", line 909, in tdm.dm.update.integrateUsrAnswer.preconditions
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/dm/tis.py", line 815, in proposition_is_acceptable
    acceptable = device_handler.is_valid_parameter(proposition, facts, self.language_code)
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/ddd/device_handler.py", line 190, in is_valid_parameter
    if self._validity_rejects_facts(validity, tested_facts, language_code):
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/ddd/device_handler.py", line 198, in _validity_rejects_facts
    if self._validity_rejects_values(validity, arguments):
  File "/usr/local/tdm/lib/python2.7/site-packages/tdm/ddd/device_handler.py", line 212, in _validity_rejects_values
    valid_parameters = apply(validity.is_valid, arguments)
  File "device.py", line 23, in is_valid
KeyError: u'contact_mary'
